[package]
name = "corona"
version = "2.0.0"
authors = [
    "whs31 <ryazantsev.dl@edu.spbstu.ru>",
]
description = "QuaSAR frontend application"

[dependencies]
cmake = { version = "0.1.2", distribution = "sources" }
leaf = { version = "0.4.1", distribution = "static" }
leafconf = { version = "0.1.2", distribution = "static" }
