[font]
family = 'Segoe UI'
pixelsize = 20
pointsize = 16
weight = 400

[meta]
name = 'gruvbox'
type = 'qml'

[palette.light]
base0 = '#f2e5bc'
base1 = '#fbf1c7'
base2 = '#f9f5d7'
blue = '#458588'
flamingo = '#d3869b'
green = '#b8bb26'
grey0 = '#4b4d56'
lavender = '#83a598'
maroon = '#9d0006'
mauve = '#8f3f71'
overlay0 = '#665c54'
overlay1 = '#504945'
overlay2 = '#3c3836'
peach = '#d65d0e'
pink = '#b16286'
red = '#fb4934'
rosewater = '#b57614'
sapphire = '#076678'
sky = '#427b58'
subtext0 = '#32302f'
subtext1 = '#282828'
surface0 = '#a89984'
surface1 = '#928374'
surface2 = '#7c6f64'
teal = '#689d6a'
text = '#1d2021'
yellow = '#fabd2f'

[palette.dark]
base0 = '#1d2021'
base1 = '#282828'
base2 = '#32302f'
blue = '#458588'
flamingo = '#d3869b'
green = '#b8bb26'
grey0 = '#d6d7d7'
lavender = '#83a598'
maroon = '#9d0006'
mauve = '#8f3f71'
overlay0 = '#7c6f64'
overlay1 = '#928374'
overlay2 = '#a89984'
peach = '#d65d0e'
pink = '#b16286'
red = '#fb4934'
rosewater = '#ebdbb2'
sapphire = '#076678'
sky = '#427b58'
subtext0 = '#f2e5bc'
subtext1 = '#fbf1c7'
surface0 = '#3c3836'
surface1 = '#504945'
surface2 = '#665c54'
teal = '#689d6a'
text = '#f9f5d7'
yellow = '#fabd2f'